/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
function View_VirtualScrollComponent_1(_l){return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,null,null,0,"div",[],[[4,"height","px"]],null,null,null,null))],null,function(_ck,_v){_ck(_v,0,0,_v.context.$implicit)})}function View_VirtualScrollComponent_2(_l){return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,null,null,0,"div",[],[[4,"height","px"]],null,null,null,null))],null,function(_ck,_v){_ck(_v,0,0,_v.context.$implicit)})}import*as i0 from"@angular/core";import*as i1 from"@angular/common";import*as i2 from"./virtual-scroll.component";var styles_VirtualScrollComponent=[],RenderType_VirtualScrollComponent=i0.ɵcrt({encapsulation:2,styles:styles_VirtualScrollComponent,data:{}});export{RenderType_VirtualScrollComponent};export function View_VirtualScrollComponent_0(_l){return i0.ɵvid(0,[i0.ɵqud(402653184,1,{bodyRef:0}),i0.ɵqud(402653184,2,{topRef:0}),i0.ɵqud(402653184,3,{bottomRef:0}),i0.ɵqud(402653184,4,{contentRef:0}),(_l()(),i0.ɵeld(4,0,[[1,0],["body",1]],null,8,"div",[["class","scroll-body f-full"]],null,null,null,null,null)),(_l()(),i0.ɵeld(5,0,[[2,0],["top",1]],null,2,"div",[["class","scroll-top"]],null,null,null,null,null)),(_l()(),i0.ɵand(16777216,null,null,1,null,View_VirtualScrollComponent_1)),i0.ɵdid(7,278528,null,0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,"ngForOf"]},null),(_l()(),i0.ɵeld(8,0,[[4,0],["content",1]],null,1,"div",[["class","scroll-content"]],null,null,null,null,null)),i0.ɵncd(null,0),(_l()(),i0.ɵeld(10,0,[[3,0],["bottom",1]],null,2,"div",[["class","scroll-bottom"]],null,null,null,null,null)),(_l()(),i0.ɵand(16777216,null,null,1,null,View_VirtualScrollComponent_2)),i0.ɵdid(12,278528,null,0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,"ngForOf"]},null)],function(_ck,_v){var _co=_v.component;_ck(_v,7,0,_co.topHeights),_ck(_v,12,0,_co.bottomHeights)},null)};export function View_VirtualScrollComponent_Host_0(_l){return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,null,null,1,"eui-virtual-scroll",[["class","f-column panel-noscroll"]],null,null,null,View_VirtualScrollComponent_0,RenderType_VirtualScrollComponent)),i0.ɵdid(1,4243456,null,0,i2.VirtualScrollComponent,[i0.ChangeDetectorRef,i0.Renderer2],null,null)],null,null)};var VirtualScrollComponentNgFactory=i0.ɵccf("eui-virtual-scroll",i2.VirtualScrollComponent,View_VirtualScrollComponent_Host_0,{width:"width",minWidth:"minWidth",maxWidth:"maxWidth",height:"height",minHeight:"minHeight",maxHeight:"maxHeight",lazy:"lazy",rowHeight:"rowHeight",maxDivHeight:"maxDivHeight",maxVisibleHeight:"maxVisibleHeight",pageNumber:"pageNumber",pageSize:"pageSize",total:"total",data:"data"},{onUpdate:"update",onPageChange:"pageChange",bodyScroll:"bodyScroll"},["*"]);export{VirtualScrollComponentNgFactory};