/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r};import{NgModule}from"@angular/core";import{CommonModule}from"@angular/common";import{FormsModule}from"@angular/forms";import{BaseModule}from"../base/base.module";import{GridBaseModule}from"../gridbase/grid-base.module";import{PaginationModule}from"../pagination/pagination.module";import{TreeGridComponent}from"./treegrid.component";import{TreeGridBodyComponent}from"./treegrid-body.component";import{TreeGridViewComponent}from"./treegrid-view.component";import{TreeGridRowComponent}from"./treegrid-row.component";import{TreeGridChildrenComponent}from"./treegrid-children.component";import{TreeGridEditTemplateDirective}from"./treegrid-edittemplate.directive";var TreeGridModule=function(){function TreeGridModule(){}return TreeGridModule=__decorate([NgModule({declarations:[TreeGridComponent,TreeGridBodyComponent,TreeGridViewComponent,TreeGridRowComponent,TreeGridChildrenComponent,TreeGridEditTemplateDirective],imports:[CommonModule,FormsModule,BaseModule,GridBaseModule,PaginationModule],exports:[TreeGridComponent,TreeGridBodyComponent,TreeGridViewComponent,TreeGridRowComponent,TreeGridChildrenComponent,TreeGridEditTemplateDirective]})],TreeGridModule)}();export{TreeGridModule};