/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r};import{NgModule}from"@angular/core";import{CommonModule}from"@angular/common";import{FormsModule}from"@angular/forms";import{BaseModule}from"../base/base.module";import{PaginationModule}from"../pagination/pagination.module";import{GridBaseModule}from"../gridbase/grid-base.module";import{DataGridComponent}from"./datagrid.component";import{DataGridBodyComponent}from"./datagrid-body.component";import{DataGridViewComponent}from"./datagrid-view.component";import{DataGridTableComponent}from"./datagrid-table.component";import{DataGridGroupTemplateDirective}from"./datagrid-grouptemplate.directive";import{DataGridDetailTemplateDirective}from"./datagrid-detailtemplate.directive";import{DataGridEditTemplateDirective}from"./datagrid-edittemplate.directive";var DataGridModule=function(){function DataGridModule(){}return DataGridModule=__decorate([NgModule({declarations:[DataGridComponent,DataGridBodyComponent,DataGridViewComponent,DataGridTableComponent,DataGridGroupTemplateDirective,DataGridDetailTemplateDirective,DataGridEditTemplateDirective],imports:[CommonModule,FormsModule,BaseModule,PaginationModule,GridBaseModule],exports:[DataGridComponent,DataGridBodyComponent,DataGridViewComponent,DataGridTableComponent,DataGridGroupTemplateDirective,DataGridDetailTemplateDirective,DataGridEditTemplateDirective]})],DataGridModule)}();export{DataGridModule};