/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __extends=this&&this.__extends||function(){var extendStatics=function(d,b){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,b){d.__proto__=b}||function(d,b){for(var p in b)b.hasOwnProperty(p)&&(d[p]=b[p])})(d,b)};return function(d,b){function __(){this.constructor=d}extendStatics(d,b),d.prototype=null===b?Object.create(b):(__.prototype=b.prototype,new __)}}(),__decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r},__metadata=this&&this.__metadata||function(k,v){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(k,v)};import{Component,forwardRef,Input}from"@angular/core";import{NG_VALUE_ACCESSOR}from"@angular/forms";import{SPINNER_BASE_TEMPLATE}from"../base/spinner-base.component";import{TimeSpinnerComponent}from"../timespinner/timespinner.component";var DateTimeSpinnerComponent=function(_super){function DateTimeSpinnerComponent(){var _this=null!==_super&&_super.apply(this,arguments)||this;return _this.selections=[[0,2],[3,5],[6,10],[11,13],[14,16],[17,19]],_this._format="MM/dd/yyyy HH:mm",_this}__extends(DateTimeSpinnerComponent,_super),DateTimeSpinnerComponent_1=DateTimeSpinnerComponent;var DateTimeSpinnerComponent_1;return __decorate([Input(),__metadata("design:type",Object)],DateTimeSpinnerComponent.prototype,"selections",void 0),DateTimeSpinnerComponent=DateTimeSpinnerComponent_1=__decorate([Component({selector:"eui-datetimespinner",template:SPINNER_BASE_TEMPLATE,providers:[{provide:NG_VALUE_ACCESSOR,useExisting:forwardRef(function(){return DateTimeSpinnerComponent_1}),multi:!0}],host:{"[class.f-inline-row]":"true","[class.f-field]":"true"}})],DateTimeSpinnerComponent)}(TimeSpinnerComponent);export{DateTimeSpinnerComponent};