/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __extends=this&&this.__extends||function(){var extendStatics=function(d,b){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,b){d.__proto__=b}||function(d,b){for(var p in b)b.hasOwnProperty(p)&&(d[p]=b[p])})(d,b)};return function(d,b){function __(){this.constructor=d}extendStatics(d,b),d.prototype=null===b?Object.create(b):(__.prototype=b.prototype,new __)}}(),__decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r},__metadata=this&&this.__metadata||function(k,v){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(k,v)},__param=this&&this.__param||function(paramIndex,decorator){return function(target,key){decorator(target,key,paramIndex)}};import{Component,Inject,Host,forwardRef}from"@angular/core";import{GridBodyComponent}from"../gridbase/grid-body.component";import{TreeGridViewComponent}from"./treegrid-view.component";export var TREEGRID_BODY_TEMPLATE='\n\t<div #body class="datagrid-body f-full" (scroll)="onScroll($event)">\n\t\t<div #inner class="datagrid-body-inner">\n\t\t\t<div euiTreeGridChildren [rows]="rows" [columns]="columns">\n\t\t\t</div>\n\t\t</div>\n\t</div>\n';var TreeGridBodyComponent=function(_super){function TreeGridBodyComponent(view){var _this=_super.call(this)||this;return _this.view=view,_this}return __extends(TreeGridBodyComponent,_super),TreeGridBodyComponent=__decorate([Component({selector:"eui-treegrid-body",template:TREEGRID_BODY_TEMPLATE,host:{class:"f-column f-full"}}),__param(0,Host()),__param(0,Inject(forwardRef(function(){return TreeGridViewComponent}))),__metadata("design:paramtypes",[TreeGridViewComponent])],TreeGridBodyComponent)}(GridBodyComponent);export{TreeGridBodyComponent};