/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r},__metadata=this&&this.__metadata||function(k,v){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(k,v)},__param=this&&this.__param||function(paramIndex,decorator){return function(target,key){decorator(target,key,paramIndex)}};import{Component,ViewChild,ElementRef,Host,Inject,forwardRef}from"@angular/core";import{PaginationComponent}from"./pagination.component";var PaginationListComponent=function(){function PaginationListComponent(pagination){this.pagination=pagination}return PaginationListComponent.prototype.ngAfterViewInit=function(){this.listRef.nativeElement.value||(this.listRef.nativeElement.value=this.pagination.pageList[0]),this.pagination.pageSize=this.listRef.nativeElement.value},PaginationListComponent.prototype.onChange=function(event){event.stopPropagation(),this.pagination.pageSize=this.listRef.nativeElement.value},__decorate([ViewChild("list"),__metadata("design:type",ElementRef)],PaginationListComponent.prototype,"listRef",void 0),PaginationListComponent=__decorate([Component({selector:"eui-pagination-list",template:'\n\t\t<select #list class="pagination-page-list" (change)="onChange($event)">\n\t\t\t<option *ngFor="let page of pagination.pageList" [selected]="page==pagination.pageSize">{{page}}</option>\n\t\t</select>\n\t',host:{class:"f-inline-row"}}),__param(0,Host()),__param(0,Inject(forwardRef(function(){return PaginationComponent}))),__metadata("design:paramtypes",[PaginationComponent])],PaginationListComponent)}();export{PaginationListComponent};