/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r},__metadata=this&&this.__metadata||function(k,v){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(k,v)};import{Component,ContentChildren,forwardRef,QueryList,Input}from"@angular/core";import{LinkButtonComponent}from"./linkbutton.component";var ButtonGroupComponent=function(){function ButtonGroupComponent(){this.selectionMode="multiple"}return ButtonGroupComponent.prototype.ngAfterContentInit=function(){var _this=this;this.initButtons(),this.buttons.changes.subscribe(function(){return _this.initButtons()})},ButtonGroupComponent.prototype.initButtons=function(){var _this=this;this.buttons.length&&this.buttons.forEach(function(btn){btn.click.subscribe(function(){"single"==_this.selectionMode&&_this.buttons.filter(function(b){return b!=btn}).forEach(function(b){b.selected=!1})})})},__decorate([ContentChildren(forwardRef(function(){return LinkButtonComponent})),__metadata("design:type",QueryList)],ButtonGroupComponent.prototype,"buttons",void 0),__decorate([Input(),__metadata("design:type",String)],ButtonGroupComponent.prototype,"selectionMode",void 0),ButtonGroupComponent=__decorate([Component({selector:"eui-button-group",template:"<ng-content></ng-content>",host:{class:"f-inline-row"}})],ButtonGroupComponent)}();export{ButtonGroupComponent};