/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r};import{NgModule}from"@angular/core";import{CommonModule}from"@angular/common";import{FormsModule}from"@angular/forms";import{InputBaseComponent}from"./input-base.component";import{SpinnerBaseComponent}from"./spinner-base.component";import{ComboBaseComponent}from"./combo-base.component";import{ListBaseComponent}from"./list-base.component";import{AddonComponent}from"./addon.component";import{VirtualScrollComponent}from"./virtual-scroll.component";import{ItemTemplateDirective}from"./template-base";import{HeaderTemplateDirective}from"./template-base";import{BodyTemplateDirective}from"./template-base";import{CellTemplateDirective}from"./template-base";import{EditTemplateDirective}from"./template-base";import{FooterTemplateDirective}from"./template-base";import{FilterTemplateDirective}from"./template-base";import{GroupTemplateDirective}from"./template-base";import{DetailTemplateDirective}from"./template-base";import{PageTemplateDirective}from"./template-base";import{LabelDirective}from"./label.directive";import{SlideUpDownDirective}from"./slide-updown.directive";var BaseModule=function(){function BaseModule(){}return BaseModule=__decorate([NgModule({declarations:[InputBaseComponent,SpinnerBaseComponent,ComboBaseComponent,ListBaseComponent,AddonComponent,VirtualScrollComponent,ItemTemplateDirective,HeaderTemplateDirective,BodyTemplateDirective,CellTemplateDirective,EditTemplateDirective,FooterTemplateDirective,FilterTemplateDirective,GroupTemplateDirective,DetailTemplateDirective,PageTemplateDirective,LabelDirective,SlideUpDownDirective],imports:[CommonModule,FormsModule],exports:[InputBaseComponent,SpinnerBaseComponent,ComboBaseComponent,ListBaseComponent,AddonComponent,VirtualScrollComponent,ItemTemplateDirective,HeaderTemplateDirective,BodyTemplateDirective,CellTemplateDirective,EditTemplateDirective,FooterTemplateDirective,FilterTemplateDirective,GroupTemplateDirective,DetailTemplateDirective,PageTemplateDirective,LabelDirective,SlideUpDownDirective]})],BaseModule)}();export{BaseModule};