/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r},__metadata=this&&this.__metadata||function(k,v){if("object"==typeof Reflect&&"function"==typeof Reflect.metadata)return Reflect.metadata(k,v)};import{Directive,Input,ElementRef}from"@angular/core";import{domHelper}from"../base/domhelper";var SlideUpDownDirective=function(){function SlideUpDownDirective(hostRef){this.hostRef=hostRef,this.animate=!1,this.disabled=!1,this.viewInited=!1,this._collapsed=!1}return Object.defineProperty(SlideUpDownDirective.prototype,"collapsed",{get:function(){return this._collapsed},set:function(value){if(value!=this._collapsed&&(this._collapsed=value,!this.disabled&&this.viewInited)){var el=this.hostRef.nativeElement;this.animate?this._collapsed?domHelper.slideUp(el):domHelper.slideDown(el):this._collapsed?domHelper.addClass(el,"f-hide"):domHelper.removeClass(el,"f-hide")}},enumerable:!0,configurable:!0}),SlideUpDownDirective.prototype.ngAfterViewInit=function(){var _this=this;if(this.disabled)return!1;this.viewInited||setTimeout(function(){_this.viewInited=!0,_this.collapsed&&domHelper.addClass(_this.hostRef.nativeElement,"f-hide")})},__decorate([Input(),__metadata("design:type",Boolean)],SlideUpDownDirective.prototype,"animate",void 0),__decorate([Input(),__metadata("design:type",Boolean)],SlideUpDownDirective.prototype,"disabled",void 0),__decorate([Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],SlideUpDownDirective.prototype,"collapsed",null),SlideUpDownDirective=__decorate([Directive({selector:"[euiSlideUpDown]"}),__metadata("design:paramtypes",[ElementRef])],SlideUpDownDirective)}();export{SlideUpDownDirective};