/**
 * EasyUI for Angular 1.2.5
 * 
 * Copyright (c) 2009-2019 www.jeasyui.com. All rights reserved.
 *
 * Licensed under the freeware license: https://www.jeasyui.com/license_freeware2.php
 * To use it on other terms please contact us: info@jeasyui.com
 *
 */
var __decorate=this&&this.__decorate||function(decorators,target,key,desc){var d,c=arguments.length,r=c<3?target:null===desc?desc=Object.getOwnPropertyDescriptor(target,key):desc;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)r=Reflect.decorate(decorators,target,key,desc);else for(var i=decorators.length-1;i>=0;i--)(d=decorators[i])&&(r=(c<3?d(r):c>3?d(target,key,r):d(target,key))||r);return c>3&&r&&Object.defineProperty(target,key,r),r};import{NgModule}from"@angular/core";import{CommonModule}from"@angular/common";import{FormsModule}from"@angular/forms";import{BaseModule}from"../base/base.module";import{PaginationModule}from"../pagination/pagination.module";import{ComboBoxModule}from"../combobox/combobox.module";import{DataListModule}from"../datalist/datalist.module";import{GridBaseComponent}from"./grid-base.component";import{GridColumnComponent}from"./grid-column.component";import{GridHeaderComponent}from"./grid-header.component";import{GridBodyComponent}from"./grid-body.component";import{GridFooterComponent}from"./grid-footer.component";import{GridColumnGroupComponent}from"./grid-column-group.component";import{GridHeaderRowComponent}from"./grid-header-row.component";import{GridFilterRowComponent}from"./grid-filter-row.component";import{GridViewComponent}from"./grid-view.component";import{GridHeaderTemplateDirective}from"./grid-headertemplate.directive";import{GridCellTemplateDirective}from"./grid-celltemplate.directive";import{GridFilterTemplateDirective}from"./grid-filtertemplate.directive";import{GridFilterButtonComponent}from"./grid-filter-button.component";import{ResizableModule}from"../resizable/resizable.module";var GridBaseModule=function(){function GridBaseModule(){}return GridBaseModule=__decorate([NgModule({declarations:[GridBaseComponent,GridColumnComponent,GridHeaderComponent,GridBodyComponent,GridFooterComponent,GridColumnGroupComponent,GridHeaderRowComponent,GridFilterRowComponent,GridViewComponent,GridHeaderTemplateDirective,GridCellTemplateDirective,GridFilterTemplateDirective,GridFilterButtonComponent],imports:[CommonModule,FormsModule,BaseModule,PaginationModule,ComboBoxModule,DataListModule,ResizableModule],exports:[GridBaseComponent,GridColumnComponent,GridHeaderComponent,GridBodyComponent,GridFooterComponent,GridColumnGroupComponent,GridHeaderRowComponent,GridFilterRowComponent,GridViewComponent,GridHeaderTemplateDirective,GridCellTemplateDirective,GridFilterTemplateDirective,GridFilterButtonComponent]})],GridBaseModule)}();export{GridBaseModule};