DELETE FROM TB_MENUINF_NEW;
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000000','시스템관리',null,'JINT','1','F',null,'1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000001','공통관리',null,'JINT','1','F','0000000000','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000002','권한관리',null,'JINT','1','F','0000000000','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000003','로그관리',null,'JINT','1','F','0000000000','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000004','공통코드등록','SY_comCdRegMgmt','JINT','1','M','0000000001','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000005','센터정보등록','SY_ctrInfRegMgmt','JINT','1','M','0000000001','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000006','환경설정','SY_Env','JINT','1','M','0000000001','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000007','프로그램등록관리','SY_pgmRegMgmt','JINT','1','M','0000000002','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000008','메뉴등록관리','SY_menuRegMgmt','JINT','1','M','0000000002','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000009','사용자등록관리','SY_userRegMgmt','JINT','1','M','0000000002','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000010','사용자등록관리','CM_adminSelPop','JINT','1','M','0000000002','4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000011','권한그룹권한등록관리','SY_authGrpAuthReg','JINT','1','M','0000000002','5','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000012','권한그룹등록관리','SY_authGrpRegMgmt','JINT','1','M','0000000002','6','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000013','프로그램로그조회','SY_pgmLogSel','JINT','1','M','0000000003','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000014','주문관리',null,'JINT','1','F',null,'2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000015','주문등록관리',null,'JINT','1','F','0000000014','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000016','주문진행관리',null,'JINT','1','F','0000000014','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000017','주문집계관리',null,'JINT','1','F','0000000014','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000018','주문등록조회','OR_reg','JINT','1','M','0000000015','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000019','주문진행현황조회','OR_progress','JINT','1','M','0000000016','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000020','주문집계조회','OR_total','JINT','1','M','0000000017','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000021','생산관리',null,'JINT','1','F',null,'3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000022','제조지시관리',null,'JINT','1','F','0000000021','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000023','생산계획관리',null,'JINT','1','F','0000000021','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000024','생산실적관리',null,'JINT','1','F','0000000021','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000025','제품포장관리',null,'JINT','1','F','0000000021','4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000026','진행현황관리',null,'JINT','1','F','0000000021','5','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000027','제조지시등록','PROD_MForderReg','JINT','1','M','0000000022','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000028','제조지시 조회 및 삭제','PROD_MForderShDel','JINT','1','M','0000000022','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000029','생산계획등록','PROD_planReg','JINT','1','M','0000000023','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000030','생산계획대비실적조회','PROD_planShDel','JINT','1','M','0000000023','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000031','생산실적등록','PROD_resultReg','JINT','1','M','0000000024','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000032','생산실적조회 및 삭제','PROD_resultShDel','JINT','1','M','0000000024','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000033','제품생산현황 집계조회','PROD_resultTotal','JINT','1','M','0000000024','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000034','제품포장실적등록','PROD_packReg','JINT','1','M','0000000025','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000035','제품포장실적조회및삭제','PROD_packShDel','JINT','1','M','0000000025','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000036','진행현황모니터링','PROD_progressStat','JINT','1','M','0000000026','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000037','출하관리',null,'JINT','1','F',null,'4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000038','제품입고',null,'JINT','1','F','0000000037','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000039','제품출고',null,'JINT','1','F','0000000037','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000040','제품재고',null,'JINT','1','F','0000000037','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000041','제품입고등록','SHIP_inReg','JINT','1','M','0000000038','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000042','제품입고실적 조회 및 삭제','SHIP_inResultShDel','JINT','1','M','0000000038','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000043','제품출고등록','SHIP_outReg','JINT','1','M','0000000039','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000044','제품출고실적 조회 및 삭제','SHIP_outResultShDel','JINT','1','M','0000000039','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000045','제품재고조회','SHIP_stockSh','JINT','1','M','0000000040','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000046','제품입출고 집계조회(고객사별)','SHIP_stockIoTotalShClnt','JINT','1','M','0000000040','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000047','제품입출고 집계조회(제품별)','SHIP_stockIoTotalShProd','JINT','1','M','0000000040','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000048','제품재고 집계조회','SHIP_stockTotalSh','JINT','1','M','0000000040','4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000049','품질관리',null,'JINT','1','F',null,'5','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000050','불량품실적관리',null,'JINT','1','F','0000000049','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000051','반품실적관리',null,'JINT','1','F','0000000049','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000052','불량품 실적 조회','QUAL_defectRate','JINT','1','M','0000000050','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000053','반품실적 등록','QUAL_returnReg','JINT','1','M','0000000051','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000054','반품실적 조회 및 삭제','QUAL_returnResult','JINT','1','M','0000000051','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000055','원자재관리',null,'JINT','1','F',null,'6','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000056','원자재 입고',null,'JINT','1','F','0000000055','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000057','원자재 출고',null,'JINT','1','F','0000000055','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000058','원자재 재고',null,'JINT','1','F','0000000055','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000059','자재입고등록조회','MTRL_inRegSh','JINT','1','M','0000000056','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000060','자재출고등록','MTRL_outReg','JINT','1','M','0000000057','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000061','자재출고실적 조회 및 삭제','MTRL_outShDel','JINT','1','M','0000000057','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000062','자재재고조회','MTRL_stockSh','JINT','1','M','0000000058','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000063','자재입출고 집계조회(공급사별)','MTRL_stockIoTotalShSpl','JINT','1','M','0000000058','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000064','자재입출고 집계조회(자재별)','MTRL_stockIoTotalShMtrl','JINT','1','M','0000000058','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000065','자재재고 집계조회','MTRL_stockTotalSh','JINT','1','M','0000000058','4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000066','기준정보관리',null,'JINT','1','F',null,'7','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000067','자재',null,'JINT','1','F','0000000066','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000068','제품',null,'JINT','1','F','0000000066','2','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000069','고객사',null,'JINT','1','F','0000000066','3','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000070','공급사','COM_product','JINT','1','F','0000000066','4','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000071','자재코드 관리 조회및 등록,수정, 삭제','COM_Material','JINT','1','M','0000000067','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000072','제품코드 관리 조회및 등록,수정, 삭제','COM_Customer','JINT','1','M','0000000068','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000073','고객사코드 관리 조회및 등록,수정, 삭제','COM_Supplier','JINT','1','M','0000000069','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
insert into TB_MENUINF_NEW (AUTH_CODE, MENU_ID, MENU_NAME, PGM_ID, APT_CD, COMP_CD, MENU_DIV, UP_MENU_ID, MENU_ORDER, USE_YN, REG_DT, REG_USER_NO, REG_PGM_ID, UPD_DT, UPD_USER_NO, UPD_PGM_ID, TASK_DIV, SEARCH_AUTH, PRINT_AUTH, INPUT_AUTH)
values ('MEMB','0000000074','공급사코드 관리 조회및 등록,수정, 삭제','','JINT','1','M','0000000070','1','Y',SYSDATE(),'jkkim','jkkim',null,null,null,'001','Y','Y','Y');
